kubectl delete service log-output-svc
kubectl delete service ping-pong-svc
kubectl delete service todo-project-backend-svc
kubectl delete ingress log-output-ingress
kubectl delete deployment log-output-dep
kubectl delete deployment ping-pong-dep
kubectl delete deployment todo-project-backend-dep
kubectl delete pvc log-output-ping-pong-pvc
kubectl delete pv log-output-ping-pong-pv
